# I/O
data_dir: data         # Root directory of raw or processed data

cat_features: ['User', 'Card', 'Use Chip',
       'Merchant Name', 'Merchant City', 'Merchant State', 'Zip', 'MCC',
       'Errors?', 'Year','Month','Day','Hour']

# ───────────── training loop hyper-parameters ────────────────────────────────
total_epochs: 50      # Number of training epochs
batch_size:   256     # Batch size for training
lr:        2.19e-4   # Initial learning rate
window:       10       # Sequence length (transactions per sample)
stride:       10       # Stride length between windows
# ───────────── feature lists ────────────────────────────────────────────────
cat_features:
  - User
  - Card
  - Use Chip
  - Merchant Name
  - Merchant City
  - Merchant State
  - Zip
  - MCC
  - Errors?
  - Year
  - Month
  - Day
  - Hour
cont_features:
  - Amount  

# 
unfreeze:    True               

lstm_hidden:  792
lstm_layers:  1
lstm_classes: 1
lstm_dropout: 0.1