# I/O
data_dir: data         # Root directory of raw or processed data

head: lstm
# ------------- training loop hyper-parameters --------------------------------
total_epochs: 50      # Number of training epochs
batch_size:   120     # Batch size for training
lr:           1.0e-3  # Initial learning rate
window:       10       # Sequence length (transactions per sample)
stride:       10       # Stride length between windows
# ------------- feature lists ------------------------------------------------
cat_features:
  - User
  - Card
  - Use Chip
  - Merchant Name
  - Merchant City
  - Merchant State
  - Zip
  - MCC
  - Errors?
  - Year
  - Month
  - Day
  - Hour
cont_features:
  - Amount  

mlp_hidden_size: 1080
mlp_num_layers: 3
mlp_dropout: 0.1


lstm_hidden:  1080
lstm_layers:  1
lstm_classes: 1
lstm_dropout: 0.1