# I/O
data_dir: data         # Root directory of raw or processed data

cat_features: ['User', 'Card', 'Use Chip',
       'Merchant Name', 'Merchant City', 'Merchant State', 'Zip', 'MCC',
       'Errors?', 'Year','Month','Day','Hour']

# ------------- training loop hyper-parameters --------------------------------
total_epochs: 50      # Number of training epochs
batch_size:   32     # Batch size for training
lr:           5.0e-5  # Initial learning rate
window:       10       # Sequence length (transactions per sample)
stride:       10       # Stride length between windows
# ------------- feature lists ------------------------------------------------
cat_features:
  - User
  - Card
  - Use Chip
  - Merchant Name
  - Merchant City
  - Merchant State
  - Zip
  - MCC
  - Errors?
  - Year
  - Month
  - Day
  - Hour
cont_features:
  - Amount  

mlp_hidden_size: 512
mlp_num_layers: 2
mlp_dropout: 0.1

unfreeze:  True               

# lstm_hidden:  0
# lstm_layers:  0
# lstm_classes: 0
# lstm_dropout: 0