# I/O
data_dir:    data         # folder with transactions.csv or processed_data.pt
window:      20
cat_features: ['User', 'Card', 'Use Chip',
       'Merchant Name', 'Merchant City', 'Merchant State', 'Zip', 'MCC',
       'Errors?', 'Year','Month','Day','Time']

cont_features: ["Amount"]
# training
epochs:      10
batch_size:  32
lr:          5e-4

# model
emb_dim:     48
dropout:     0.10
field_tf:
  d_model:   48
  n_heads:   4
  depth:     1
sequence_tf:
  d_model:   256
  n_heads:   4
  depth:     4
