# sweep.yaml
# W&B hyper-parameter sweep for TransactionModel
# ─────────────────────────────────────────────────────────────────────────────
# ‣ We keep `batch_size`, `cat_features`, and `cont_features` fixed.
# ‣ We start with 3 training epochs per trial—enough to gauge throughput
#   and relative loss trends without spending too much time.
# ‣ Objective: minimise validation loss (change the metric name if yours differs).
# -----------------------------------------------------------------------------
program: train_pretrain.py          # entry-point that calls wandb.init()
method: bayes              # Bayesian optimisation over the search space

metric:
  name:  val_loss
  goal: minimize

parameters:

  # ─────────── fixed knobs ───────────
  total_epochs:
    value: 3               # quick runs; bump later for full training
  batch_size:
    value: 320             # discovered sweet-spot
  # cat_features / cont_features come from the YAML config you load in train.py

  # ─────────── data windowing ───────────
  window:
    values: [10, 50]
  stride:
    values: [5, 10, 25, 50]

  # ─────────── optimiser ───────────
  lr:                      # try 1e-5 … 3e-3 on a log scale
    distribution: log_uniform_values
    min: 1e-5
    max: 3e-3

  # ─────────── embedding layer ───────────
  emb_dropout:
    distribution: uniform
    min: 0.0
    max: 0.20

  # ─────────── field-level transformer ───────────
  ft_d_model:
    values: [32, 48, 64, 128]           # divisible by every ft_n_heads choice
  ft_depth:
    values: [1, 2, 3]
  ft_n_heads:
    values: [2, 4, 8]
  ft_ffn_mult:
    values: [2, 4]
  ft_dropout:
    distribution: uniform
    min: 0.0
    max: 0.20

  # ─────────── sequence-level transformer ───────────
  seq_d_model:
    values: [256, 320, 384, 512]
  seq_depth:
    values: [1, 2, 3, 4, 5]
  seq_n_heads:
    values: [4, 8, 16, 32]
  seq_ffn_mult:
    values: [4, 8]
  seq_dropout:
    distribution: uniform
    min: 0.0
    max: 0.20

  # ─────────── classifier head ───────────
  clf_dropout:
    distribution: uniform
    min: 0.0
    max: 0.30
